In [3]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

home_df = pd.read_csv('home_data.csv')

home_df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

# Question 1

**Selection and summary statistics**: We found the zip code with the highest average house price. What is the average house price of that zip code?

In [4]:
import numpy

zip_df = home_df[['zipcode','price']]

zip_df = zip_df.sort_values(by = ['zipcode'])

#zip_df = zip_df.set_index('zipcode')

zip_df = zip_df.groupby(['zipcode']).mean().sort_values(by = ['price'])

zip_df.tail(1)

             price
zipcode
98039    2160606.6

# Question 2

**Filtering data**: What fraction of the houses have living space between 2000 sq.ft. and 4000 sq.ft.?

In [5]:
sqft_living_df = home_df[['id', 'sqft_living']]

sqft_living_2000_to_4000_df = sqft_living_df[sqft_living_df['sqft_living'].between(2000, 4000)]

print(float(sqft_living_2000_to_4000_df.shape[0]) / float(sqft_living_df.shape[0]))

0.4266413732475825

# Question 3

**Building a regression model with several more features**: What is the difference in RMSE between the model trained with my_features and the one trained with advanced_features?

my_features = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'zipcode']

advanced_features = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'zipcode',
'condition', # condition of house
'grade', # measure of quality of construction
'waterfront', # waterfront property
'view', # type of view
'sqft_above', # square feet above ground
'sqft_basement', # square feet in basement
'yr_built', # the year built
'yr_renovated', # the year renovated
'lat', 'long', # the lat-long of the parcel
'sqft_living15', # average sq.ft. of 15 nearest neighbors
'sqft_lot15', # average lot size of 15 nearest neighbors]

In [13]:
my_features = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'zipcode']
y = home_df['price']


advanced_features = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'zipcode',
'condition', # condition of house
'grade', # measure of quality of construction
'waterfront', # waterfront property
'view', # type of view
'sqft_above', # square feet above ground
'sqft_basement', # square feet in basement
'yr_built', # the year built
'yr_renovated', # the year renovated
'lat', 'long', # the lat-long of the parcel
'sqft_living15', # average sq.ft. of 15 nearest neighbors
'sqft_lot15' # average lot size of 15 nearest neighbors
                    ]

X_advanced = home_df[advanced_features]
X_advanced

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,zipcode,condition,grade,waterfront,view,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,98178,3,7,0,0,1180,0,1955,0,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,98125,3,7,0,0,2170,400,1951,1991,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,98028,3,6,0,0,770,0,1933,0,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,98136,5,7,0,0,1050,910,1965,0,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,98074,3,8,0,0,1680,0,1987,0,47.6168,-122.045,1800,7503
5,4,4.50,5420,101930,1.0,98053,3,11,0,0,3890,1530,2001,0,47.6561,-122.005,4760,101930
6,3,2.25,1715,6819,2.0,98003,3,7,0,0,1715,0,1995,0,47.3097,-122.327,2238,6819
7,3,1.50,1060,9711,1.0,98198,3,7,0,0,1060,0,1963,0,47.4095,-122.315,1650,9711
8,3,1.00,1780,7470,1.0,98146,3,7,0,0,1050,730,1960,0,47.5123,-122.337,1780,8113
9,3,2.50,1890,6560,2.0,98038,3,7,0,0,1890,0,2003,0,47.3684,-122.031,2390,7570
10,3,2.50,3560,9796,1.0,98007,3,8,0,0,1860,1700,1965,0,47.6007,-122.145,2210,8925
11,2,1.00,1160,6000,1.0,98115,4,7,0,0,860,300,1942,0,47.6900,-122.292,1330,6000
12,3,1.00,1430,19901,1.5,98028,4,7,0,0,1430,0,1927,0,47.7558,-122.229,1780,12697
13,3,1.75,1370,9680,1.0,98074,4,7,0,0,1370,0,1977,0,47.6127,-122.045,1370,10208
14,5,2.00,1810,4850,1.5,98107,3,7,0,0,1810,0,1900,0,47.6700,-122.394,1360,4850
15,4,3.00,2950,5000,2.0,98126,3,9,0,3,1980,970,1979,0,47.5714,-122.375,2140,4000
16,3,2.00,1890,14040,2.0,98019,3,7,0,0,1890,0,1994,0,47.7277,-121.962,1890,14018
17,4,1.00,1600,4300,1.5,98103,4,7,0,0,1600,0,1916,0,47.6648,-122.343,1610,4300
18,2,1.00,1200,9850,1.0,98002,4,7,0,0,1200,0,1921,0,47.3089,-122.210,1060,5095
19,3,1.00,1250,9774,1.0,98003,4,7,0,0,1250,0,1969,0,47.3343,-122.306,1280,8850
20,4,1.75,1620,4980,1.0,98133,4,7,0,0,860,760,1947,0,47.7025,-122.341,1400,4980
21,3,2.75,3050,44867,1.0,98040,3,9,0,4,2330,720,1968,0,47.5316,-122.233,4110,20336
22,5,2.50,2270,6300,2.0,98092,3,8,0,0,2270,0,1995,0,47.3266,-122.169,2240,7005
23,2,1.50,1070,9643,1.0,98030,3,7,0,0,1070,0,1985,0,47.3533,-122.166,1220,8386
24,3,2.25,2450,6500,2.0,98030,4,8,0,0,2450,0,1985,0,47.3739,-122.172,2200,6865
25,3,2.00,1710,4697,1.5,98002,5,6,0,0,1710,0,1941,0,47.3048,-122.218,1030,4705
26,3,1.75,2450,2691,2.0,98119,3,8,0,0,1750,700,1915,0,47.6386,-122.360,1760,3573
27,3,1.00,1400,1581,1.5,98112,5,8,0,0,1400,0,1909,0,47.6221,-122.314,1860,3861
28,3,1.75,1520,6380,1.0,98115,3,7,0,0,790,730,1948,0,47.6950,-122.304,1520,6235
29,4,2.50,2570,7173,2.0,98052,3,8,0,0,2570,0,2005,0,47.7073,-122.110,2630,6026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21583,2,1.00,710,1157,2.0,98102,4,7,0,0,710,0,1943,0,47.6413,-122.329,1370,1173
21584,3,2.50,1260,900,2.0,98116,3,7,0,0,940,320,2007,0,47.5621,-122.384,1310,1415
21585,3,2.50,1870,5000,2.0,98042,3,7,0,0,1870,0,2009,0,47.3339,-122.055,2170,5399
21586,2,2.50,1430,1201,3.0,98107,3,8,0,0,1430,0,2009,0,47.6707,-122.381,1430,1249
21587,3,2.50,1520,1488,3.0,98125,3,8,0,0,1520,0,2006,0,47.7337,-122.309,1520,1497
21588,2,1.50,1210,1278,2.0,98117,3,8,0,0,1020,190,2007,0,47.6756,-122.375,1210,1118
21589,3,2.50,2540,4760,2.0,98038,3,8,0,0,2540,0,2010,0,47.3452,-122.022,2540,4571
21590,4,3.50,4910,9444,1.5,98074,3,11,0,0,3110,1800,2007,0,47.6502,-122.066,4560,11063
21591,4,2.75,2770,3852,2.0,98178,3,8,0,0,2770,0,2014,0,47.5001,-122.232,1810,5641
21592,3,2.25,1190,1200,3.0,98103,3,8,0,0,1190,0,2008,0,47.6542,-122.346,1180,1224
21593,5,3.75,4170,8142,2.0,98056,3,10,0,2,4170,0,2006,0,47.5354,-122.181,3030,7980
21594,4,2.75,2500,5995,2.0,98042,3,8,0,0,2500,0,2008,0,47.3749,-122.107,2530,5988
21595,2,2.25,1530,981,3.0,98103,3,8,0,0,1480,50,2006,0,47.6533,-122.346,1530,1282
21596,5,2.75,3600,9437,2.0,98059,3,9,0,0,3600,0,2014,0,47.4822,-122.131,3550,9421
21597,4,3.25,3410,10125,2.0,98040,3,10,0,0,3410,0,2007,0,47.5653,-122.223,2290,10125
21598,4,2.50,3118,7866,2.0,98001,3,9,0,2,3118,0,2014,0,47.2931,-122.264,2673,6500
21599,4,3.00,3990,7838,2.0,98053,3,9,0,0,3990,0,2003,0,47.6857,-122.046,3370,6814
21600,5,3.75,4470,8088,2.0,98004,3,11,0,0,4470,0,2008,0,47.6321,-122.200,2780,8964
21601,3,2.50,1425,1179,3.0,98125,3,8,0,0,1425,0,2008,0,47.6963,-122.318,1285,1253
21602,3,1.75,1500,11968,1.0,98010,3,6,0,0,1500,0,2014,0,47.3095,-122.002,1320,11303
21603,3,2.50,2270,5536,2.0,98065,3,8,0,0,2270,0,2003,0,47.5389,-121.881,2270,5731
21604,3,2.00,1490,1126,3.0,98144,3,8,0,0,1490,0,2014,0,47.5699,-122.288,1400,1230
21605,4,2.50,2520,6023,2.0,98056,3,9,0,0,2520,0,2014,0,47.5137,-122.167,2520,6023
21606,4,3.50,3510,7200,2.0,98136,3,9,0,0,2600,910,2009,0,47.5537,-122.398,2050,6200
21607,3,2.50,1310,1294,2.0,98116,3,8,0,0,1180,130,2008,0,47.5773,-122.409,1330,1265
21608,3,2.50,1530,1131,3.0,98103,3,8,0,0,1530,0,2009,0,47.6993,-122.346,1530,1509
21609,4,2.50,2310,5813,2.0,98146,3,8,0,0,2310,0,2014,0,47.5107,-122.362,1830,7200
21610,2,0.75,1020,1350,2.0,98144,3,7,0,0,1020,0,2009,0,47.5944,-122.299,1020,2007
21611,3,2.50,1600,2388,2.0,98027,3,8,0,0,1600,0,2004,0,47.5345,-122.069,1410,1287
21612,2,0.75,1020,1076,2.0,98144,3,7,0,0,1020,0,2008,0,47.5941,-122.299,1020,1357

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from math import sqrt


X_advanced_train, X_advanced_test, y_train, y_test = train_test_split(X_advanced, y,test_size=0.2, random_state = 42)

X_my_train = X_advanced_train[my_features]
X_my_test = X_advanced_test[my_features]

linreg_my = LinearRegression().fit(X_my_train, y_train)
linreg_ad = LinearRegression().fit(X_advanced_train, y_train)
print(linreg_my.coef_)
print(linreg_ad.coef_)

print(linreg_my.score(X_my_test, y_test))
print(linreg_ad.score(X_advanced_test, y_test))

y_my_pred = linreg_my.predict(X_my_test)
y_advanced_pred = linreg_ad.predict(X_advanced_test)
print(sqrt(mean_squared_error(y_test, y_my_pred)) - sqrt(mean_squared_error(y_test, y_advanced_pred)))

[ -5.66723924e+04   1.65476422e+04   3.13063049e+02  -3.20232174e-01
  -5.76662072e+03   5.81860332e+02]
[ -3.43354189e+04   4.45645358e+04   1.09015816e+02   8.88473505e-02
   7.00312462e+03  -5.52253009e+02   2.45267105e+04   9.45678906e+04
   5.62413071e+05   5.36411067e+04   7.00227412e+01   3.89930748e+01
  -2.68076897e+03   2.04156320e+01   5.95968123e+05  -1.94585720e+05
   2.12143281e+01  -3.25831855e-01]
0.515217682596
0.701190442637
58177.67226499258

In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from math import sqrt

advance = advanced_features + ['price']

home_advance = home_df[advance]

train_data, test_data = train_test_split(home_advance, test_size=0.8, random_state=42)

lin_reg_ad = LinearRegression().fit(train_data[advanced_features], train_data['price'])
lin_reg_my = LinearRegression().fit(train_data[my_features], train_data['price'])

y_ad_predict = lin_reg_ad.predict(test_data[advanced_features])
y_my_predict = lin_reg_my.predict(test_data[my_features])

print(sqrt(mean_squared_error(test_data['price'], y_my_predict)) - sqrt(mean_squared_error(test_data['price'], y_ad_predict)))

53745.86330736554